"""Chat router: RAG-powered conversational Q&A."""

import json
import traceback
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from models.schemas import ChatRequest
from services.rag import chat as rag_chat, chat_stream

router = APIRouter()


@router.post("/chat")
async def chat(req: ChatRequest):
    """
    RAG chat endpoint (non-streaming).
    """
    try:
        result = rag_chat(req.workspace_id, req.message)
        return result
    except Exception as e:
        print(f"CHAT ERROR: {str(e)}")
        traceback.print_exc()
        raise HTTPException(500, f"Chat error: {str(e)}")


@router.get("/chat/stream")
async def chat_stream_endpoint(
    workspace_id: str = Query(...), message: str = Query(...)
):
    """
    Streaming chat endpoint using SSE (Server-Sent Events).
    Yields text chunks as they're generated by the LLM.
    """

    async def event_generator():
        try:
            for chunk in chat_stream(workspace_id, message):
                # SSE format: data: <content>\n\n
                yield f"data: {chunk}\n\n"
            # End of stream marker
            yield "data: [DONE]\n\n"
        except Exception as e:
            print(f"STREAM ERROR: {str(e)}")
            traceback.print_exc()
            yield f"data: ERROR: {str(e)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "Access-Control-Allow-Origin": "*",
        },
    )
